version: '3.7'

services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: crowd
      MYSQL_USER: admin
      MYSQL_PASSWORD: crowd
      MYSQL_ROOT_PASSWORD: pestillo

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1